### ISSUE TITLE
骗人的程序

### ISSUE THREAD

**Issue by anzisheng** [borgishmorg/CUDAPhotoProcessing#1]
你的cuda代码根本不起作用。你通过拷贝填充了new_picture 了

**Comment by borgishmorg** [comment]
親愛的朋友，請注意第62行，有一個對內核的調用，使圖片變得模糊。

我還想指出，這個代碼是我在大學的實驗室工作，已成功接受。儲存庫中還有範例圖片。這意味著程式碼可以工作，但你錯了。

最好的祝愿！
